#!/usr/bin/env python3.1
from copy import copy, deepcopy
import json
import sys

def system_to_input(system):
    """generates input for gravity.py from a dictionary representing an orbital system"""

    return deepcopy(system)

def main(in_filename="-", out_filename="-"):
    in_file  = open(in_filename,  "rt") if in_filename  != "-" else sys.stdin
    out_file = open(out_filename, "wt") if out_filename != "-" else sys.stdout
    
    with in_file, out_file:
        in_dict = json.load(in_file)
        out_dict = system_to_input(in_dict)
        json.dump(out_dict, out_file, indent=2)

if __name__ == "__main__":
    sys.exit(main(*sys.argv[1:]))
